# Generated by Django 3.0.4 on 2020-10-12 04:53

import apps.definitions.models
from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import spices.django3.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("coreobjects", "0004_accountingbankaccount"),
    ]

    operations = [
        migrations.CreateModel(
            name="Adapter",
            fields=[
                ("last_modified_date", models.DateTimeField(auto_now=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    spices.django3.fields.PrefixedIdField(
                        prefix="adp", primary_key=True, serialize=False
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=50, unique=True)),
                ("url", models.TextField()),
                (
                    "channel",
                    models.CharField(
                        choices=[("WEB", "Web"), ("FTP", "FTP")],
                        default="WEB",
                        max_length=50,
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                ("backlog_priority_rank", models.IntegerField(blank=True, null=True)),
                (
                    "created_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="definitions_adapter_created_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_modified_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="definitions_adapter_last_modified_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("default_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Connector",
            fields=[
                ("last_modified_date", models.DateTimeField(auto_now=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    spices.django3.fields.PrefixedIdField(
                        prefix="conn", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.TextField()),
                ("login_url", models.TextField(blank=True, null=True)),
                (
                    "registration_url",
                    models.TextField(blank=True, default=None, null=True),
                ),
                ("enabled", models.BooleanField(default=None)),
                (
                    "type",
                    models.CharField(
                        choices=[("VENDOR", "Vendor"), ("ACCOUNTING", "Accounting")],
                        default=None,
                        max_length=50,
                    ),
                ),
                (
                    "icon",
                    models.FileField(
                        blank=True,
                        max_length=512,
                        null=True,
                        storage=django.core.files.storage.FileSystemStorage(
                            "assets/images/logos/integrator/"
                        ),
                        upload_to=apps.definitions.models.generate_image_name,
                    ),
                ),
                (
                    "adapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="connectors",
                        to="definitions.Adapter",
                    ),
                ),
                (
                    "created_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="definitions_connector_created_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_modified_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="definitions_connector_last_modified_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("default_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="ConnectorVendorInfo",
            fields=[
                ("last_modified_date", models.DateTimeField(auto_now=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "connector",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        related_name="connector_vendor",
                        serialize=False,
                        to="definitions.Connector",
                    ),
                ),
                ("contains_support_document", models.BooleanField(default=None)),
                ("requires_account_number", models.BooleanField(default=False)),
                (
                    "created_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="definitions_connectorvendorinfo_created_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_modified_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="definitions_connectorvendorinfo_last_modified_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vendor_cvis",
                        to="coreobjects.SharedCoreObjectModel",
                    ),
                ),
                (
                    "vendor_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vendor_group_cvis",
                        to="coreobjects.SharedCoreObjectModel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("default_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="ConnectorEntityIntegration",
            fields=[
                ("last_modified_date", models.DateTimeField(auto_now=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    spices.django3.fields.PrefixedIdField(
                        prefix="conei", primary_key=True, serialize=False
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("bank_account", "Bank Account"),
                            ("gl_account", "GL Account"),
                            ("invoice", "Invoice"),
                            ("payment", "Payment Information"),
                            ("statement", "Statement"),
                            ("vendor", "Vendor"),
                        ],
                        max_length=100,
                    ),
                ),
                ("supports_import", models.BooleanField()),
                ("supports_export", models.BooleanField()),
                (
                    "import_format",
                    models.TextField(
                        blank=True,
                        choices=[
                            ("pdf", "pdf"),
                            ("csv", "csv"),
                            ("xls", "xls"),
                            ("json", "json"),
                        ],
                    ),
                ),
                (
                    "connector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entity_integrations",
                        to="definitions.Connector",
                    ),
                ),
                (
                    "created_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="definitions_connectorentityintegration_created_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_modified_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="definitions_connectorentityintegration_last_modified_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("connector", "entity_type")},
            },
            managers=[
                ("default_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
