# Generated by Django 3.0.4 on 2020-12-16 13:16

import apps.definitions.models
from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ("definitions", "0001_squashed_0029_auto_20200820_0858"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connectorentityintegration",
            name="entity_type",
            field=models.CharField(
                choices=[
                    ("bank_account", "Bank Account"),
                    ("gl_account", "GL Account"),
                    ("invoice", "Invoice"),
                    ("payment", "Payment Information"),
                    ("statement", "Statement"),
                    ("vendor", "Vendor"),
                    ("order_guide", "Order Guide"),
                    ("purchase_order", "Purchase Order"),
                ],
                max_length=100,
            ),
        ),
    ]
