# Generated by Django 3.0.4 on 2021-02-09 06:08

import apps.definitions.models
from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ("definitions", "0002_auto_20201216_0516"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adapter",
            name="enabled",
        ),
    ]
