# Generated by Django 3.0.4 on 2021-03-01 10:43

import apps.definitions.models
from django.db import migrations, models
import spices.django3.fields
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ("definitions", "0003_auto_20210208_2208"),
    ]

    operations = [
        migrations.AddField(
            model_name="connector",
            name="disabled_reason",
            field=spices.django3.fields.CharChoiceField(
                blank=True,
                choices=apps.definitions.models.ConnectorDisabledReason,
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="connector",
            name="disabled_reason_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
