# Generated by Django 3.0.4 on 2021-03-09 07:13

import apps.definitions.models
from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ("definitions", "0004_auto_20210301_0243"),
    ]

    operations = [
        migrations.AddField(
            model_name="connector",
            name="hidden",
            field=models.BooleanField(default=False),
        ),
    ]
