# Generated by Django 3.0.4 on 2021-03-26 10:35

import apps.definitions.models
from django.db import migrations, models
import spices.django3.fields
import storages.backends.s3boto3


class Migration(migrations.Migration):
    dependencies = [
        ("definitions", "0005_auto_20210308_2313"),
    ]

    operations = [
        migrations.AddField(
            model_name="connector",
            name="adapter_code",
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="connector",
            name="channel",
            field=spices.django3.fields.CharChoiceField(
                choices=apps.definitions.models.Channel,
                default=apps.definitions.models.Channel["WEB"],
                max_length=50,
            ),
        ),
    ]
