# Generated by Django 3.0.4 on 2021-04-05 11:07

import apps.definitions.models
from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ("definitions", "0006_auto_20210326_0335"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="connector",
            name="adapter",
        ),
        migrations.DeleteModel(
            name="Adapter",
        ),
    ]
