# Generated by Django 3.0.4 on 2021-04-14 09:57

import apps.definitions.models
from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):
    dependencies = [
        ("definitions", "0007_auto_20210405_0407"),
    ]

    operations = [
        migrations.AddField(
            model_name="connector",
            name="backlog_rank",
            field=models.IntegerField(null=True, blank=True),
        )
    ]
