# Generated by Django 3.0.4 on 2021-04-15 08:37

import apps.definitions.models
from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ("definitions", "0008_auto_20210414_0257"),
    ]

    operations = [
        migrations.AddField(
            model_name="connector",
            name="etd_date",
            field=models.DateTimeField(blank=True, default=None, null=True),
        )
    ]
