# Generated by Django 3.0.4 on 2021-04-14 19:52

import apps.definitions.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import spices.django3.fields
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("definitions", "0009_auto_20210415_0137"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConnectorCapability",
            fields=[
                ("last_modified_date", models.DateTimeField(auto_now=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    spices.django3.fields.PrefixedIdField(
                        prefix="concp", primary_key=True, serialize=False
                    ),
                ),
                (
                    "type",
                    spices.django3.fields.CharChoiceField(
                        choices=apps.definitions.models.ConnectorCapabilityTypes,
                        max_length=256,
                    ),
                ),
                (
                    "supported_file_format",
                    spices.django3.fields.CharChoiceField(
                        blank=True,
                        choices=apps.definitions.models.SupportedFileType,
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "connector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="capabilities",
                        to="definitions.Connector",
                    ),
                ),
                (
                    "created_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="definitions_connectorcapability_created_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_modified_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="definitions_connectorcapability_last_modified_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("connector", "type")},
            },
            managers=[
                ("default_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
