# Generated by Django 3.0.4 on 2021-05-10 16:16

import apps.definitions.models
from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ("definitions", "0011_migrate_connector_entity_to_connector_capabilities"),
    ]

    operations = [
        migrations.AddField(
            model_name="connector",
            name="frequency",
            field=models.IntegerField(blank=True, null=True),
        )
    ]
