# Generated by Django 3.0.4 on 2021-05-24 13:10

import apps.definitions.models
from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ("definitions", "0013_add_web_internal_login_capability"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ConnectorEntityIntegration",
        ),
    ]
