# Generated by Django 3.0.4 on 2021-06-10 07:06

import apps.definitions.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ("definitions", "0014_auto_20210524_0610"),
    ]

    operations = [
        migrations.AddField(
            model_name="connector",
            name="custom_properties",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=None, null=True
            ),
        )
    ]
