# Generated by Django 3.0.4 on 2021-06-16 13:42

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("definitions", "0015_auto_20210610_0006"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connector",
            name="custom_properties",
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        )
    ]
