# Generated by Django 3.0.4 on 2021-06-18 07:39

import apps.definitions.models
from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ("definitions", "0016_auto_20210616_0642"),
    ]

    operations = [
        migrations.AddField(
            model_name="connector",
            name="invoice_download_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="connector",
            name="video_url",
            field=models.TextField(blank=True, null=True),
        ),
    ]
