# Generated by Django 3.0.4 on 2021-06-18 07:39

import apps.definitions.models
from django.db import migrations, models
import storages.backends.s3boto3
from apps.runs.management.commands import LOGGER


def get_invoice_url(adapter_code):
    return {
        "att": "http://att.com/acctmgmt/accountoverview",
        "baldor": "https://www.baldorfood.com/account-home/invoices-and-orders",
        "southern_glazers_of_ca_south": "https://shop.sgproof.com/sgws/en/usd/Invoices",
        "cox_business": "https://myaccount.coxbusiness.com/cbma/billing/viewmystatements",
        "las_vegas_valley_water_district": "https://myaccount.lvvwd.com/bill-history.cfml",
        "wbmason": "https://www.wbmason.com/InvoiceHistory.aspx",
        "usfoods": "https://www3.usfoods.com/order/faces/oracle/webcenter/portalapp/pages/invoice/invoiceInquiry.jspx",
        "unfi": "https://customers.unfi.com/Pages/OrderHistory.aspx",
        "uline": "https://www.uline.com/MyAccount/Invoices",
        "sysco_account_center": "https://sysco.accountcenter.com/customer/reports/invoice",
        "sysco": "https://corasysco.force.com/v2/s/history",
        "staples": "https://www.staples.com/ptd/myorders",
        "southwest_gas": "https://myaccount.swgas.com/Portal/#/billinghistory",
        "socalgas": "https://business.socalgas.com/portal/faces/adf.task-flow?adf.tfId=bill-history-flow&adf.tfDoc=/WEB-INF/taskflows/billHistory/bill-history-flow.xml&_adf.ctrl-state=yloi7l0vu_90&nodeId=billHistory913913136",
        "smart_food_service": "https://www.chefstore.com/account/receiptmanager/",
        "slemco": "https://slemco.smarthub.coop/#billHistory:",
        "restaurant_technologies_inc": "http://www.rtitom.com/MyAccount/BillingHistory.aspx",
        "restaurant_depot": "https://member.restaurantdepot.com/receipts",
        "nw_natural": "https://ipn2.paymentus.com/cp/oidc/nwng/bills",
        "mid_american_energy_services": "https://www.midamericanenergyservices.com/EMA/Bills/Main",
        "ipfone": "https://ipfone.billcenter.net/Bills/default.aspx",
        "fintech": "https://www.fintech.net/fms/reports/retailer_invoice_information_detailed.asp",
        "filpac": "https://customerportal.filpac.net/Main/invoices.aspx",
        "benekeith": "https://shop.benekeith.com/#/invoices/",
    }.get(adapter_code, "")


def add_invoices_url_to_connector(apps, schema_editor):
    Connector = apps.get_model("definitions", "Connector")
    objects = models.Manager()
    objects.model = Connector
    LOGGER.info("[STARTED] Migration of connectors for internal.web_login capability")

    connectors = list(objects.filter(enabled=True))
    for connector in connectors:
        connector.invoice_download_url = get_invoice_url(connector.adapter_code)
        connector.save()
    LOGGER.info("[COMPLETED] Migration of connectors for internal.web_login capability")


class Migration(migrations.Migration):
    dependencies = [
        ("definitions", "0017_auto_20210618_0039"),
    ]

    operations = [migrations.RunPython(add_invoices_url_to_connector, atomic=True)]
