import environ

env = environ.Env()

DRIVER_DEFAULT_IMPLICIT_WAIT = 15
DRIVER_DEFAULT_EXPLICIT_WAIT = 20
DRIVER_EXECUTABLE_PATH = "/app/chromedriver"

TEMP_DOWNLOAD_DIR = "/tmp/downloads"
REMOVE_FILES_OLDER_THAN_MINUTES = 3 * 60  # 6 hours

RUN_RETRY_COUNT = env.int("RUN_RETRY_COUNT", default=2)
RUN_NOT_SUCCESS_COUNT_INTERVAL = env.int("RUN_NOT_SUCCESS_COUNT_INTERVAL", default=12)
SUCCESS_RUN_INTERVAL = env.float("SUCCESS_RUN_INTERVAL", default=23.9)
