# Generated by Django 3.0.4 on 2020-10-12 05:21

import django.db.models.manager
import django_better_admin_arrayfield.models.fields
from django.conf import settings
from django.db import migrations, models

import spices.django3.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("coreobjects", "0004_accountingbankaccount"),
        ("credentials", "0002_auto_20200902_0343"),
        ("definitions", "0001_squashed_0029_auto_20200820_0858"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                ("last_modified_date", models.DateTimeField(auto_now=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    spices.django3.fields.PrefixedIdField(
                        prefix="job", primary_key=True, serialize=False
                    ),
                ),
                ("username", models.TextField()),
                ("password", spices.django3.fields.EncryptedTextField()),
                ("enabled", models.BooleanField(default=False)),
                (
                    "candidate_restaurant_ids",
                    django_better_admin_arrayfield.models.fields.ArrayField(
                        base_field=models.IntegerField(),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
                ("edi_job_id", models.TextField(blank=True, null=True)),
                ("create_missing_vendors", models.NullBooleanField(default=False)),
                ("notes", models.TextField(blank=True, max_length=500, null=True)),
                (
                    "invoice_email",
                    django_better_admin_arrayfield.models.fields.ArrayField(
                        base_field=models.EmailField(max_length=256),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="account_jobs",
                        to="coreobjects.SharedCoreObjectModel",
                    ),
                ),
                (
                    "connector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="jobs",
                        to="definitions.Connector",
                    ),
                ),
                (
                    "created_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobconfig_job_created_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ftp_credential",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs",
                        to="credentials.FTPCredential",
                    ),
                ),
                (
                    "last_modified_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobconfig_job_last_modified_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="location_jobs",
                        to="coreobjects.SharedCoreObjectModel",
                    ),
                ),
                (
                    "location_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="location_group_jobs",
                        to="coreobjects.SharedCoreObjectModel",
                    ),
                ),
            ],
            options={
                "unique_together": {("connector", "username")},
            },
            managers=[
                ("default_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="PIQMapping",
            fields=[
                ("last_modified_date", models.DateTimeField(auto_now=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    spices.django3.fields.PrefixedIdField(
                        prefix="piqmap", primary_key=True, serialize=False
                    ),
                ),
                ("mapping_data", models.TextField()),
                ("mapped_to", models.TextField(blank=True, null=True)),
                (
                    "created_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobconfig_piqmapping_created_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="piq_mappings",
                        to="jobconfig.Job",
                    ),
                ),
                (
                    "last_modified_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobconfig_piqmapping_last_modified_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "piq_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scom_piq_mappings",
                        to="coreobjects.SharedCoreObjectModel",
                    ),
                ),
            ],
            options={
                "unique_together": {("job", "piq_data", "mapping_data")},
            },
            managers=[
                ("default_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="FileDiscoveryAction",
            fields=[
                ("last_modified_date", models.DateTimeField(auto_now=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    spices.django3.fields.PrefixedIdField(
                        prefix="fdact", primary_key=True, serialize=False
                    ),
                ),
                (
                    "document_type",
                    models.TextField(
                        choices=[
                            ("invoice", "Invoice"),
                            ("statement", "Statement"),
                            ("po", "Purchase Order"),
                            ("pickup_slip", "Pickup Slip"),
                            ("packing_slip", "Packing Slip"),
                        ]
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("none", "Do nothing"),
                            ("piq_nonedi", "Upload to Plate IQ (non EDI Invoice)"),
                            ("piq_edi", "Upload to Plate IQ (EDI Invoice)"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "edi_parser_code",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("810", "810"),
                            ("piq", "PlateIQ"),
                            ("piq_json", "PlateIQ JSON Invoice Format"),
                            ("fintech", "Fintech"),
                            ("baldor", "Baldor"),
                            ("bergin", "Bergin"),
                            ("singer", "Singer"),
                            ("staples", "Staples"),
                            ("us_foods_webedi", "USFoods (WebEDI)"),
                            ("service_channel", "ServiceChannel"),
                            ("amazon", "Amazon"),
                            ("fedex", "Fedex"),
                            ("westcoast", "WestCoast"),
                            ("benkeith", "Ben E. Keith"),
                            ("restaurant_depot_webedi", "Restaurant Depot (WebEDI)"),
                            ("doordash_webedi", "DoorDash (WebEDI)"),
                            ("doordash_cava", "DoorDash Cava (WebEDI)"),
                            ("txu_webedi", "TXU Energy (WebEDI)"),
                            ("loomis_torchys", "Loomis Torchys"),
                            ("nationalwaste_torchys", "National Waste Torchys"),
                            ("fuze_cava", "Fuze Cava"),
                            (
                                "smart_food_service",
                                "Smartfood Service (formerly Cash&Carry)",
                            ),
                            (
                                "enterprise_fleet_management",
                                "Enterprise Fleet Management",
                            ),
                            ("sysco_webedi", "Sysco (WebEDI)"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "created_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobconfig_filediscoveryaction_created_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_discovery_actions",
                        to="jobconfig.Job",
                    ),
                ),
                (
                    "last_modified_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobconfig_filediscoveryaction_last_modified_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("job", "document_type")},
            },
            managers=[
                ("default_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="CustomerMapping",
            fields=[
                ("last_modified_date", models.DateTimeField(auto_now=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    spices.django3.fields.PrefixedIdField(
                        prefix="cnmap", primary_key=True, serialize=False
                    ),
                ),
                ("customer_number", models.CharField(max_length=128)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "created_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobconfig_customermapping_created_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customer_number_mappings",
                        to="jobconfig.Job",
                    ),
                ),
                (
                    "last_modified_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobconfig_customermapping_last_modified_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="location_customer_number_mappings",
                        to="coreobjects.SharedCoreObjectModel",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vendor_customer_number_mappings",
                        to="coreobjects.SharedCoreObjectModel",
                    ),
                ),
            ],
            options={
                "unique_together": {("job", "customer_number")},
            },
            managers=[
                ("default_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
