# Generated by Django 3.0.4 on 2020-10-12 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("definitions", "0001_squashed_0029_auto_20200820_0858"),
        ("jobconfig", "0001_squashed_20201012"),
    ]

    operations = [
        migrations.AddField(
            model_name="filediscoveryaction",
            name="connector",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="document_discovery_actions",
                to="definitions.Connector",
            ),
        ),
        migrations.AlterField(
            model_name="filediscoveryaction",
            name="job",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="document_discovery_actions",
                to="jobconfig.Job",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="filediscoveryaction",
            unique_together={("connector", "document_type"), ("job", "document_type")},
        ),
    ]
