# Generated by Django 3.0.4 on 2020-10-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobconfig", "0002_auto_20201012_0447"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filediscoveryaction",
            name="document_type",
            field=models.TextField(
                choices=[
                    ("invoice", "Invoice"),
                    ("statement", "Statement"),
                    ("po", "Purchase Order"),
                    ("pickup_slip", "Pickup Slip"),
                    ("packing_slip", "Packing Slip"),
                    ("receipt", "Receipt"),
                ]
            ),
        ),
    ]
