# Generated by Django 3.0.4 on 2020-12-17 09:14

import apps.definitions.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import spices.django3.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("coreobjects", "0004_accountingbankaccount"),
        ("jobconfig", "0003_auto_20201029_0448"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConnectorRequest",
            fields=[
                ("last_modified_date", models.DateTimeField(auto_now=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    spices.django3.fields.PrefixedIdField(
                        prefix="conreq", primary_key=True, serialize=False
                    ),
                ),
                ("is_deleted", models.NullBooleanField(default=False)),
                (
                    "deleted_id",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "type",
                    spices.django3.fields.CharChoiceField(
                        choices=apps.definitions.models.ConnectorType, max_length=50
                    ),
                ),
                ("name", models.TextField()),
                ("login_url", models.TextField()),
                ("username", models.TextField()),
                ("password", spices.django3.fields.EncryptedTextField(blank=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="account_connector_requests",
                        to="coreobjects.SharedCoreObjectModel",
                    ),
                ),
                (
                    "created_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobconfig_connectorrequest_created_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_modified_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobconfig_connectorrequest_last_modified_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
