# Generated by Django 3.0.4 on 2020-12-21 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobconfig", "0004_connectorrequest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="edi_job_id",
        ),
    ]
