# Generated by Django 3.0.4 on 2021-01-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coreobjects", "0004_accountingbankaccount"),
        ("jobconfig", "0005_remove_job_edi_job_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="companies",
            field=models.ManyToManyField(
                blank=True, null=True, to="coreobjects.SharedCoreObjectModel"
            ),
        ),
    ]
