# Generated by Django 3.0.4 on 2021-01-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coreobjects", "0004_accountingbankaccount"),
        ("jobconfig", "0007_company_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="login_url",
            field=models.TextField(blank=True, null=False, default=""),
        ),
        migrations.AlterField(
            model_name="job",
            name="companies",
            field=models.ManyToManyField(
                blank=True,
                related_name="company_jobs",
                to="coreobjects.SharedCoreObjectModel",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="job",
            unique_together={("connector", "username", "login_url")},
        ),
    ]
