# Generated by Django 3.0.4 on 2021-02-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobconfig", "0008_auto_20210119_0132"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="job",
            managers=[],
        ),
        migrations.AddField(
            model_name="job",
            name="deleted_id",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="is_deleted",
            field=models.NullBooleanField(default=False),
        ),
    ]
