# Generated by Django 3.0.4 on 2021-03-08 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("jobconfig", "0009_auto_20210223_1058"),
    ]

    operations = [
        migrations.AddField(
            model_name="connectorrequest",
            name="converted_to_job",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="jobconfig.Job",
            ),
        ),
    ]
