# Generated by Django 3.0.4 on 2021-03-10 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("jobconfig", "0010_connectorrequest_converted_to_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="connectorrequest",
            name="converted_to_connector",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="definitions.Connector",
            ),
        ),
    ]
