# Generated by Django 3.0.4 on 2021-03-12 09:08

import apps.jobconfig.models
from django.db import migrations, models
import spices.django3.fields


class Migration(migrations.Migration):

    dependencies = [
        ("jobconfig", "0011_connectorrequest_converted_to_connector"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="disabled_reason",
            field=spices.django3.fields.CharChoiceField(
                blank=True,
                choices=apps.jobconfig.models.JobDisabledReason,
                max_length=128,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="disabled_reason_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
