# Generated by Django 3.0.4 on 2021-03-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobconfig", "0012_auto_20210312_0108"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filediscoveryaction",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("none", "Do nothing"),
                    ("piq_nonedi", "Upload to Plate IQ (non EDI Invoice)"),
                    ("piq_edi", "Upload to Plate IQ (EDI Invoice)"),
                    ("payments_edi_upload", "Upload payments to EDI"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="filediscoveryaction",
            name="document_type",
            field=models.TextField(
                choices=[
                    ("invoice", "Invoice"),
                    ("statement", "Statement"),
                    ("po", "Purchase Order"),
                    ("pickup_slip", "Pickup Slip"),
                    ("packing_slip", "Packing Slip"),
                    ("receipt", "Receipt"),
                    ("payment", "Payment"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="filediscoveryaction",
            name="edi_parser_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("810", "810"),
                    ("piq", "PlateIQ"),
                    ("piq_json", "PlateIQ JSON Invoice Format"),
                    ("fintech", "Fintech"),
                    ("baldor", "Baldor"),
                    ("bergin", "Bergin"),
                    ("singer", "Singer"),
                    ("staples", "Staples"),
                    ("us_foods_webedi", "USFoods (WebEDI)"),
                    ("service_channel", "ServiceChannel"),
                    ("amazon", "Amazon"),
                    ("fedex", "Fedex"),
                    ("westcoast", "WestCoast"),
                    ("benkeith", "Ben E. Keith"),
                    ("restaurant_depot_webedi", "Restaurant Depot (WebEDI)"),
                    ("doordash_webedi", "DoorDash (WebEDI)"),
                    ("doordash_cava", "DoorDash Cava (WebEDI)"),
                    ("txu_webedi", "TXU Energy (WebEDI)"),
                    ("loomis_torchys", "Loomis Torchys"),
                    ("nationalwaste_torchys", "National Waste Torchys"),
                    ("fuze_cava", "Fuze Cava"),
                    ("smart_food_service", "Smartfood Service (formerly Cash&Carry)"),
                    ("enterprise_fleet_management", "Enterprise Fleet Management"),
                    ("sysco_webedi", "Sysco (WebEDI)"),
                    ("EDI_820", "EDI_820"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
