# Generated by Django 3.0.4 on 2021-04-14 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("jobconfig", "0013_auto_20210315_0654"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="disabled_at_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="disabled_by_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="job_disabled",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
