# Generated by Django 3.0.4 on 2021-05-19 20:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobconfig", "0014_auto_20210414_0724"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="custom_properties",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=None, null=True
            ),
        ),
    ]
