# Generated by Django 3.0.4 on 2021-06-01 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobconfig", "0015_job_custom_properties"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="enabled_for_manual",
            field=models.BooleanField(default=False),
        ),
    ]
