# Generated by Django 3.0.4 on 2021-06-10 09:43

import apps.jobconfig.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_better_admin_arrayfield.models.fields
import spices.django3.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("jobconfig", "0016_job_enabled_for_manual"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobStat",
            fields=[
                (
                    "id",
                    spices.django3.fields.PrefixedIdField(
                        prefix="jobstats", primary_key=True, serialize=False
                    ),
                ),
                ("date", models.DateField(verbose_name=apps.jobconfig.models.Job)),
                ("document_count", models.IntegerField()),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="jobconfig.Job",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobSchedule",
            fields=[
                ("last_modified_date", models.DateTimeField(auto_now=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    spices.django3.fields.PrefixedIdField(
                        prefix="jobsch", primary_key=True, serialize=False
                    ),
                ),
                ("is_deleted", models.NullBooleanField(default=False)),
                (
                    "deleted_id",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "week_of_month",
                    django_better_admin_arrayfield.models.fields.ArrayField(
                        base_field=models.IntegerField(blank=True, null=True),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "day_of_week",
                    django_better_admin_arrayfield.models.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("monday", "Monday"),
                                ("tuesday", "Tuesday"),
                                ("wednesday", "Wednesday"),
                                ("thursday", "Thursday"),
                                ("friday", "Friday"),
                                ("saturday", "Saturday"),
                                ("sunday", "Sunday"),
                            ],
                            max_length=20,
                            null=True,
                        ),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "date_of_month",
                    django_better_admin_arrayfield.models.fields.ArrayField(
                        base_field=models.IntegerField(
                            null=True,
                            validators=[
                                django.core.validators.MaxValueValidator(31),
                                django.core.validators.MinValueValidator(1),
                            ],
                        ),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "created_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobconfig_jobschedule_created_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="jobconfig.Job",
                    ),
                ),
                (
                    "last_modified_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobconfig_jobschedule_last_modified_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobAlertRule",
            fields=[
                ("last_modified_date", models.DateTimeField(auto_now=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    spices.django3.fields.PrefixedIdField(
                        prefix="jobrule", primary_key=True, serialize=False
                    ),
                ),
                ("is_deleted", models.NullBooleanField(default=False)),
                (
                    "deleted_id",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                ("expected_document_count", models.IntegerField()),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("day", "Day"),
                            ("week", "Week"),
                            ("month", "Month"),
                            ("fortnight", "Fortnight"),
                        ],
                        max_length=20,
                    ),
                ),
                ("period_count", models.IntegerField()),
                ("enabled", models.BooleanField()),
                (
                    "created_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobconfig_jobalertrule_created_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_rules",
                        to="jobconfig.Job",
                    ),
                ),
                (
                    "last_modified_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobconfig_jobalertrule_last_modified_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="jobstat",
            index=models.Index(fields=["job"], name="jobconfig_j_job_id_45505c_idx"),
        ),
        migrations.AddIndex(
            model_name="jobstat",
            index=models.Index(fields=["date"], name="jobconfig_j_date_3b56c2_idx"),
        ),
        migrations.AddIndex(
            model_name="jobstat",
            index=models.Index(
                fields=["job", "date"], name="jobconfig_j_job_id_f27f34_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="jobschedule",
            constraint=models.UniqueConstraint(
                condition=models.Q(_negated=True, is_deleted=True),
                fields=("job",),
                name="jobconfig_jobschedule_job_unique_exclude_deleted",
            ),
        ),
    ]
