# Generated by Django 3.0.4 on 2021-06-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobconfig", "0017_auto_20210610_0243"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jobstat",
            old_name="document_count",
            new_name="df_count",
        ),
        migrations.AddField(
            model_name="jobstat",
            name="is_customer_scheduled",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="jobstat",
            name="run_login_failure_count",
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="jobstat",
            name="run_success_count",
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="jobstat",
            name="run_total_count",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
