# Generated by Django 3.0.4 on 2021-06-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobconfig", "0018_job_stat"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobstat",
            name="run_manual_all_count",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
