# Generated by Django 3.0.4 on 2021-06-30 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobconfig", "0019_jobstat_run_manual_all_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobstat",
            name="df_count",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
