# Generated by Django 3.0.4 on 2023-07-07 10:22

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobconfig", "0020_auto_20210630_0103"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="custom_properties",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=None, null=True
            ),
        ),
    ]
