DISABLE_ACCOUNT_MESSAGES = [
    "The user ID has been locked due to too many incorrect log-in attempts. ",
    "Please contact your company’s MyAccount administrator to unlock the user account.",
    "Logon account is not active.",
    "Your account is locked due to too many invalid login attempts.",
    'Please click the "Forgot Password?" link below to follow the steps '
    "needed to reset your password and unlock your account.",
    "Your LoginID has been locked out as the maximum allowable retries has been exceeded.",
    "Please call your Customer Service Representative.",
    "Looks like you’ve tried to sign in unsuccessfully too many times.",
    "You will need to register as a new user here. "
    "The link can also be found at aramarkuniform.com under Customer Support.",
    "You haven't registered your profile yet",
    "For your security, please create a new password for your account.",
    "Your account has been locked. Please reset your password to continue.",
    "This user is disabled",
    "Your account has been locked after too many attempts",
    "We can't seem to find your account",
    "Your user is not active in any restaurant; please contact your restaurant admin or "
    "Toast support if you believe you have received this message in error.",
    "You have exceeded the maximum number of failed login attempts. Your account has been locked. "
    "You can click the Forgot Password link to unlock your account and "
    "reset your password or contact Customer Service.",
    "We’re sorry, but we can’t find an account to display.",
    "Your account is locked. Please contact your administrator.",
    "We can't log you in because of an issue with single sign-on. Contact your Salesforce admin for help.",
    "We're sorry. This user ID has been temporarily disabled.",
]
UNDER_MAINTENANCE_MESSAGES = [
    "Maintenance Underway",
    "The site is currently offline for scheduled maintenance",
    "My Account is Temporarily Unavailable",
    "The application will be down for scheduled maintenance",
    "This portal is temporarily unavailable. Please try again later. We apologize for the inconvenience.",
    "This website is scheduled for routine maintenance and will be temporarily unavailable",
    "This website will be available shortly.  Please check back in a few minutes.",
    "Sorry. We are unable to process your request at this time. Please try again later.",
]
LOGIN_FAILED_MESSAGES = [
    "The Username and Password you entered is incorrect.",
    "Some of your information isn't correct.",
    "User Name you entered does not match our record on file.",
    "Password you entered does not match our record on file.",
    "Invalid User ID/Password",
    "Invalid user id or password.",
    "Invalid login attempt.",
    "The User Name/Password combination is invalid.",
    "The account sign-in was incorrect or your account is disabled temporarily.",
    "Sorry, your email and/or password was incorrect.",
    "Your login attempt was not successful",
    "Login failed",
    "Unable to find a user with that username or password,",
    "Invalid username or password.",
    "Incorrect user ID and/or password.",
    "Unable to authenticate Login ID and Password combination.",
    "Your login attempt was not successful.",
    "Incorrect email address or password.",
    "Your username and/or password is not correct.",
    "×Your username or password was incorrect.",
    "Your login attempt has failed.",
    "Unable to authenticate LoginID and Password combination.",
    "Check your entry and try again.",
    "The username or password provided is incorrect.",
    "We're sorry, but either the email address or password you entered is incorrect.",
    "The password is incorrect",
    "Incorrect user ID or password",
    "Authentication failed, incorrect username/password",
    "The login email and/or password is incorrect.",
    "The email and password you entered do not match.",
    "The login information you entered is invalid.",
    "Either your Username or Password is incorrect.",
    "Incorrect username or password",
    "Incorrect email/username or password",
    "Authentication failed! Invalid e-mail or password.",
    "Your email or password is incorrect.",
    "Invalid User Name or Password",
    "User Name not found or password does not match.",
    "Invalid Login!",
    "Wrong email or password",
    "Please enter a valid Username/Email and Password.",
    "Incorrect user name or password.",
    "We didn't recognize the username or password you entered.",
    "The email address entered is not associated with an account.",
    "Unable to find a user with that username or password.",
    "We do not recognize your username, password, or company.",
    "Sign in failed.",
    "Username/password is invalid",
    'Your username or password was incorrect. Please try again or click one of the "Forgot Username Email?" '
    'or "Forgot Password?" links below.',
    "Unable to authenticate LoginID and Password combination. Make sure you are using the correct case.",
    "Invalid email and or password",
    "Looks like you've tried to sign in unsuccessfully too many times.",
    "This user is disabled.",
    "this account has been locked",
    "It looks like this didn’t finish loading, but refreshing the page should fix it.",
    "You've exceeded the maximum number of login attempts.",
    "Couldn't perform login at this time.",
    "Your username or password was incorrect.",
    "Your Password has expired. Please use the forgot password link or contact your Administrator.",
    "Invalid Username/Password combination",
    "The email or password is incorrect",
    "Incorrect user ID or password. Type the correct user ID and password, and try again.",
    "The email address entered is not associated with an account. Create an Account.",
    "You entered incorrect login information, try again or reset your password",
    "Invalid login or password",
    "Unable to find a user with the username and password combination that was entered",
    "The TOM User account could not be found.",
    "We’ve noticed activity that suggests your password may be compromised.",
    "Please enter a valid email address",
    "The username or password provided in the request are invalid.",
    "Update Password",
    "Your email address or username does not match our records. Please try again.",
    "It seems like you're trying to log in with a password that was changed. "
    "If you don't remember the new one, reset your password.",
    "Our system indicates that you have changed your password recently. Please try again.",
    "Invalid username/password",
    "Please provide valid username and password or click here to request username or password.",
    "Your Username and Password do not match our records",
    "Username and/ or password are incorrect.",
    "The user name or password is incorrect.",
    "Your password does not match our records. Please try again.",
    "Login failed. Entered user name or password is invalid.",
    "Invalid Username or Password. Please check and try again.",
    "Logon account is pending approval.",
    "Your login attempt was not successful. Please try again.",
    "Authentication failed! Please try again!",
    "Please enter a valid User ID and Password and try again.",
    "Invalid Email Address or Password. Please check and try again.",
    "Authentication failed! Please try again!",
    "There was a problem authenticating, please try again later.",
    "Incorrect user ID or password. Type the correct user ID and password, and try again.",
    "Invalid Account Information and/or Password",
    "Invalid email or password.",
    "You entered an incorrect user name or password.",
    "Your Email Address/User ID or password was incorrect. Please try again.(02)",
    "Your Email Address/User ID or password was incorrect. Please try again.",
    "Sorry, you must be logged in to view this page.",
    "Username/Password combination is incorrect.",
    "You have exceeded the maximum number of login attempts. Please try again after one hour.",
    "Unable to Verify your Customer Number",
    "Invalid combination. Please try again.",
    "You have attempted to log in unsuccessfully too many times. Please reset your password.",
    "Looks like you don’t have online access yet. Let's create your User ID.",
    "This info doesn't match what's in our records. Please try again.",
    "agree to the Subscriber Agreement",
    "Your password is expired",
]
