# Generated by Django 3.0.4 on 2020-10-12 05:25

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import spices.django3.fields
import spices.django3.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("definitions", "0001_squashed_0029_auto_20200820_0858"),
        ("jobconfig", "0001_squashed_20201012"),
        ("issues", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Run",
            fields=[
                ("last_modified_date", models.DateTimeField(auto_now=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    spices.django3.fields.PrefixedIdField(
                        prefix="run", primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Created"),
                            (1, "Scheduled"),
                            (2, "Started"),
                            (3, "Succeeded"),
                            (4, "Failed"),
                        ],
                        default=0,
                    ),
                ),
                ("execution_end_ts", models.DateTimeField(null=True)),
                ("execution_start_ts", models.DateTimeField(null=True)),
                ("dry_run", models.BooleanField(default=False)),
                (
                    "request_parameters",
                    django.contrib.postgres.fields.jsonb.JSONField(default=dict),
                ),
                (
                    "aws_batch_job_id",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "created_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runs_run_created_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "failure_issue",
                    models.OneToOneField(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="failed_run",
                        to="issues.Issue",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runs",
                        to="jobconfig.Job",
                    ),
                ),
                (
                    "last_modified_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runs_run_last_modified_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            managers=[
                ("default_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="ExportRequest",
            fields=[
                ("last_modified_date", models.DateTimeField(auto_now=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    spices.django3.fields.PrefixedIdField(
                        prefix="exreq", primary_key=True, serialize=False
                    ),
                ),
                ("http_request_method", models.CharField(max_length=10)),
                ("http_request_url", models.TextField()),
                (
                    "http_request_json",
                    django.contrib.postgres.fields.jsonb.JSONField(null=True),
                ),
                ("http_response_code", models.IntegerField(default=None, null=True)),
                ("http_response_body", models.TextField(default=None, null=True)),
                ("success", models.BooleanField(default=None, null=True)),
                (
                    "created_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runs_exportrequest_created_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_modified_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runs_exportrequest_last_modified_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="export_requests",
                        to="runs.Run",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("default_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="DiscoveredFile",
            fields=[
                ("last_modified_date", models.DateTimeField(auto_now=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    spices.django3.fields.PrefixedIdField(
                        prefix="discfile", primary_key=True, serialize=False
                    ),
                ),
                ("url", models.TextField(default=None, null=True)),
                (
                    "reference_code",
                    models.TextField(
                        default=None,
                        null=True,
                        validators=[
                            spices.django3.validators.validate_not_blank_string__allow_null
                        ],
                    ),
                ),
                ("original_filename", models.TextField()),
                ("original_download_url", models.TextField()),
                (
                    "file_format",
                    models.TextField(
                        choices=[
                            ("unknown", "unknown"),
                            ("pdf", "pdf"),
                            ("csv", "csv"),
                            ("xls", "xls"),
                            ("json", "json"),
                        ],
                        default="unknown",
                    ),
                ),
                (
                    "content_hash",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=50,
                        null=True,
                        validators=[
                            spices.django3.validators.validate_not_blank_string__allow_null
                        ],
                    ),
                ),
                (
                    "downloaded_successfully",
                    models.BooleanField(default=None, null=True),
                ),
                ("downloaded_at", models.DateTimeField(null=True)),
                (
                    "document_type",
                    models.TextField(
                        choices=[
                            ("invoice", "Invoice"),
                            ("statement", "Statement"),
                            ("po", "Purchase Order"),
                            ("pickup_slip", "Pickup Slip"),
                            ("packing_slip", "Packing Slip"),
                        ]
                    ),
                ),
                (
                    "document_properties",
                    django.contrib.postgres.fields.jsonb.JSONField(default=dict),
                ),
                (
                    "piq_upload_id",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True
                    ),
                ),
                (
                    "piq_container_id",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True
                    ),
                ),
                (
                    "connector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="discovered_files",
                        to="definitions.Connector",
                    ),
                ),
                (
                    "created_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runs_discoveredfile_created_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_modified_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runs_discoveredfile_last_modified_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="discovered_files",
                        to="runs.Run",
                    ),
                ),
            ],
            managers=[
                ("default_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="DiscoveredEntity",
            fields=[
                ("last_modified_date", models.DateTimeField(auto_now=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    spices.django3.fields.PrefixedIdField(
                        prefix="discentt", primary_key=True, serialize=False
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("bank_account", "Bank Account"),
                            ("gl_account", "GL Account"),
                            ("invoice", "Invoice"),
                            ("payment", "Payment Information"),
                            ("statement", "Statement"),
                            ("vendor", "Vendor"),
                        ],
                        max_length=100,
                    ),
                ),
                ("attrs", django.contrib.postgres.fields.jsonb.JSONField()),
                ("source_entity_id", models.CharField(max_length=100, null=True)),
                (
                    "created_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runs_discoveredentity_created_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "export_request",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="discovered_entities",
                        to="runs.ExportRequest",
                    ),
                ),
                (
                    "last_modified_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runs_discoveredentity_last_modified_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="discovered_entities",
                        to="runs.Run",
                    ),
                ),
            ],
            managers=[
                ("default_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="CheckRun",
            fields=[
                ("last_modified_date", models.DateTimeField(auto_now=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    spices.django3.fields.PrefixedIdField(
                        prefix="chrun", primary_key=True, serialize=False
                    ),
                ),
                ("check_run_id", models.IntegerField(default=None, null=True)),
                ("is_checkrun_success", models.BooleanField(default=None, null=True)),
                ("is_patch_success", models.BooleanField(default=None, null=True)),
                (
                    "created_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runs_checkrun_created_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "failure_issue",
                    models.OneToOneField(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="failed_checkrun",
                        to="issues.Issue",
                    ),
                ),
                (
                    "last_modified_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runs_checkrun_last_modified_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "manual_exporter_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="manually_exported_check_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="check_runs",
                        to="runs.Run",
                    ),
                ),
            ],
            managers=[
                ("default_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name="run",
            index=models.Index(
                fields=["created_date"], name="runs_run_created_3dccb7_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="discoveredfile",
            unique_together={
                ("connector", "content_hash"),
                ("connector", "reference_code"),
            },
        ),
        migrations.AlterUniqueTogether(
            name="discoveredentity",
            unique_together={("run", "type", "source_entity_id")},
        ),
        migrations.AlterUniqueTogether(
            name="checkrun",
            unique_together={("run_id", "check_run_id")},
        ),
    ]
