# Generated by Django 3.0.4 on 2020-10-29 11:48

import storages.backends.s3boto3
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("runs", "0001_squashed_20201012"),
    ]

    operations = [
        migrations.AddField(
            model_name="discoveredfile",
            name="original_file",
            field=models.FileField(
                blank=True,
                max_length=512,
                null=True,
                storage=storages.backends.s3boto3.S3Boto3Storage(
                    bucket=settings.INTEGRATOR_BUCKET,
                    default_acl="private",
                    location="discovered_files/original",
                    querystring_auth=True,
                ),
                upload_to="",
            ),
        ),
        migrations.AlterField(
            model_name="discoveredfile",
            name="document_type",
            field=models.TextField(
                choices=[
                    ("invoice", "Invoice"),
                    ("statement", "Statement"),
                    ("po", "Purchase Order"),
                    ("pickup_slip", "Pickup Slip"),
                    ("packing_slip", "Packing Slip"),
                    ("receipt", "Receipt"),
                ]
            ),
        ),
    ]
