# Generated by Django 3.0.4 on 2020-12-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runs", "0002_auto_20201029_0448"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discoveredentity",
            name="type",
            field=models.CharField(
                choices=[
                    ("bank_account", "Bank Account"),
                    ("gl_account", "GL Account"),
                    ("invoice", "Invoice"),
                    ("payment", "Payment Information"),
                    ("statement", "Statement"),
                    ("vendor", "Vendor"),
                    ("order_guide", "Order Guide"),
                    ("purchase_order", "Purchase Order"),
                ],
                max_length=100,
            ),
        ),
    ]
