# Generated by Django 3.0.4 on 2021-03-02 08:51

from django.db import migrations, models
import spices.django3.validators


class Migration(migrations.Migration):

    dependencies = [
        ("runs", "0004_auto_20210223_1058"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discoveredfile",
            name="content_hash",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=128,
                null=True,
                validators=[
                    spices.django3.validators.validate_not_blank_string__allow_null
                ],
            ),
        ),
    ]
