# Generated by Django 3.0.4 on 2021-03-04 13:02

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import spices.django3.fields


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("runs", "0005_auto_20210302_0051"),
    ]

    operations = [
        migrations.CreateModel(
            name="VendorPayment",
            fields=[
                ("last_modified_date", models.DateTimeField(auto_now=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    spices.django3.fields.PrefixedIdField(
                        prefix="vndrpmt", primary_key=True, serialize=False
                    ),
                ),
                (
                    "payment_status",
                    models.TextField(
                        choices=[
                            ("unknown", "unknown"),
                            ("success", "success"),
                            ("failed", "failed"),
                            ("mark_as_processed", "mark_as_processed"),
                        ],
                        default="unknown",
                    ),
                ),
                (
                    "payment_details",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        default=dict, null=True
                    ),
                ),
                (
                    "created_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runs_vendorpayment_created_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "failure_issue",
                    models.OneToOneField(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="failed_payment",
                        to="issues.Issue",
                    ),
                ),
                (
                    "last_modified_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runs_vendorpayment_last_modified_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vendor_payments",
                        to="runs.Run",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("default_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
