# Generated by Django 3.0.4 on 2021-03-09 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runs", "0005_auto_20210302_0051"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discoveredfile",
            name="document_type",
            field=models.TextField(
                choices=[
                    ("invoice", "Invoice"),
                    ("statement", "Statement"),
                    ("po", "Purchase Order"),
                    ("pickup_slip", "Pickup Slip"),
                    ("packing_slip", "Packing Slip"),
                    ("receipt", "Receipt"),
                    ("payment", "Payment"),
                ]
            ),
        ),
    ]
