# Generated by Django 3.0.4 on 2021-03-17 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("runs", "0006_auto_20210308_2253"),
        ("runs", "0006_vendorpayment"),
    ]

    operations = []
