# Generated by Django 3.0.4 on 2021-04-12 13:00

import apps.runs.models
import django.contrib.postgres.fields.jsonb
import django.core.files.storage
from django.db import migrations, models
import spices.django3.fields


class Migration(migrations.Migration):

    dependencies = [
        ("runs", "0007_merge_20210316_2335"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discoveredfile",
            name="file_format",
            field=models.TextField(
                choices=[
                    ("unknown", "unknown"),
                    ("pdf", "pdf"),
                    ("csv", "csv"),
                    ("xls", "xls"),
                    ("json", "json"),
                    ("xml", "xml"),
                ],
                default="unknown",
            ),
        ),
    ]
