# Generated by Django 3.0.4 on 2021-04-12 16:22

import apps.definitions.models
import apps.runs.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import spices.django3.fields


class Migration(migrations.Migration):

    dependencies = [
        ("runs", "0008_auto_20210412_0600"),
    ]

    operations = [
        migrations.AddField(
            model_name="run",
            name="action",
            field=spices.django3.fields.CharChoiceField(
                choices=apps.definitions.models.ConnectorCapabilityTypes,
                default=None,
                max_length=256,
                null=True,
            ),
        )
    ]
