# Generated by Django 3.0.4 on 2021-04-19 10:18

import apps.runs.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import spices.django3.fields


class Migration(migrations.Migration):

    dependencies = [
        ("runs", "0009_auto_20210412_0922"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkrun",
            name="is_disabled",
            field=models.BooleanField(default=None, null=True),
        )
    ]
