# Generated by Django 3.0.4 on 2021-04-21 07:02

import apps.runs.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import spices.django3.fields


class Migration(migrations.Migration):

    dependencies = [
        ("runs", "0010_auto_20210419_0318"),
    ]

    operations = [
        migrations.AlterField(
            model_name="run",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Created"),
                    (1, "Scheduled"),
                    (2, "Started"),
                    (3, "Succeeded"),
                    (4, "Failed"),
                    (5, "Canceled"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="vendorpayment",
            name="payment_details",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=None, null=True
            ),
        ),
        migrations.AlterField(
            model_name="vendorpayment",
            name="payment_status",
            field=spices.django3.fields.TextChoiceField(
                choices=apps.runs.models.PaymentStatus, default="pending"
            ),
        ),
    ]
