# Generated by Django 3.0.4 on 2021-04-21 05:56

import apps.runs.models
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import spices.django3.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("runs", "0011_auto_20210421_0002"),
    ]

    operations = [
        migrations.AddField(
            model_name="run",
            name="canceled_by_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="run_canceled",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="run",
            name="canceled_reason",
            field=spices.django3.fields.CharChoiceField(
                choices=apps.runs.models.RunCancellationReason,
                default=None,
                max_length=256,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="run",
            name="canceled_reason_text",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
