# Generated by Django 3.0.4 on 2021-04-21 11:34

import apps.runs.models
from django.db import migrations, models
import spices.django3.fields


class Migration(migrations.Migration):

    dependencies = [
        ("runs", "0012_auto_20210420_2256"),
    ]

    operations = [
        migrations.AddField(
            model_name="run",
            name="created_via",
            field=spices.django3.fields.CharChoiceField(
                choices=apps.runs.models.RunCreatedVia,
                default=None,
                max_length=256,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="run",
            index=models.Index(fields=["job"], name="runs_run_job_id_c6e145_idx"),
        ),
        migrations.AddIndex(
            model_name="run",
            index=models.Index(fields=["status"], name="runs_run_status_a3d5f7_idx"),
        ),
        migrations.AddIndex(
            model_name="run",
            index=models.Index(
                fields=["created_via"], name="runs_run_created_303535_idx"
            ),
        ),
    ]
