# Generated by Django 3.0.4 on 2021-05-13 09:56

import apps.definitions.models
from django.db import migrations
import spices.django3.fields


class Migration(migrations.Migration):

    dependencies = [
        ("runs", "0014_populate_run_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="run",
            name="action",
            field=spices.django3.fields.CharChoiceField(
                choices=apps.definitions.models.ConnectorCapabilityTypes, max_length=256
            ),
        ),
    ]
