# Generated by Django 3.0.4 on 2021-05-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runs", "0015_make_run_mandatory"),
    ]

    operations = [
        migrations.AddField(
            model_name="run",
            name="is_manual",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="run",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Created"),
                    (1, "Scheduled"),
                    (2, "Started"),
                    (3, "Succeeded"),
                    (4, "Failed"),
                    (5, "Canceled"),
                    (6, "Partially succeeded"),
                ],
                default=0,
            ),
        ),
    ]
