# Generated by Django 3.0.4 on 2021-05-24 11:11

import apps.runs.models
from django.db import migrations
import spices.django3.fields


class Migration(migrations.Migration):
    dependencies = [
        ("runs", "0016_run_is_manual"),
    ]

    operations = [
        migrations.AlterField(
            model_name="run",
            name="created_via",
            field=spices.django3.fields.CharChoiceField(
                choices=apps.runs.models.RunCreatedVia,
                default=apps.runs.models.RunCreatedVia["SCHEDULED"],
                max_length=256,
            ),
        ),
    ]
