# Generated by Django 3.0.4 on 2021-07-14 20:13

from django.db import migrations, models
import spices.django3.validators


class Migration(migrations.Migration):

    dependencies = [
        ("runs", "0017_auto_20210524_0411"),
    ]

    operations = [
        migrations.AddField(
            model_name="discoveredfile",
            name="collision_dedupe",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="discoveredfile",
            name="extracted_text_hash",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=128,
                null=True,
                validators=[
                    spices.django3.validators.validate_not_blank_string__allow_null
                ],
            ),
        ),
    ]
