# Generated by Django 3.0.4 on 2021-07-14 20:24

from django.db import migrations
from django.db.models import Q


def populate_discovered_file_content_hash_action(apps, schema_editor):
    DF = apps.get_model("runs", "DiscoveredFile")
    dfs = DF.objects.filter(
        Q(content_hash__isnull=True) | Q(content_hash__exact="")
    ).all()
    for df in dfs:
        df.content_hash = df.id
        df.save()


class Migration(migrations.Migration):
    dependencies = [
        ("runs", "0018_auto_20210714_1313"),
    ]
    operations = [
        migrations.RunPython(populate_discovered_file_content_hash_action, atomic=True),
        migrations.AlterUniqueTogether(
            name="discoveredfile",
            unique_together={
                ("content_hash", "collision_dedupe"),
                ("extracted_text_hash", "collision_dedupe"),
            },
        ),
    ]
