# Generated by Django 3.0.4 on 2021-07-14 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("runs", "0019_auto_20210714_1324"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="discoveredfile",
            name="reference_code",
        ),
    ]
