# Generated by Django 3.0.4 on 2021-07-14 21:04
import storages.backends.s3boto3
from django.conf import settings
from django.db import migrations, models

import spices.django3.validators


class Migration(migrations.Migration):
    dependencies = [
        ("runs", "0020_remove_discoveredfile_reference_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discoveredfile",
            name="original_file",
            field=models.FileField(
                blank=True,
                max_length=512,
                null=True,
                storage=storages.backends.s3boto3.S3Boto3Storage(
                    bucket=settings.INTEGRATOR_BUCKET,
                    default_acl="private",
                    location="discovered_files/original",
                    querystring_auth=True,
                ),
                upload_to="",
                validators=[
                    spices.django3.validators.validate_not_blank_string__allow_null
                ],
            ),
        ),
    ]
