# Generated by Django 3.0.4 on 2021-07-16 19:56

from django.db import migrations, models
import spices.django3.validators


class Migration(migrations.Migration):

    dependencies = [
        ("runs", "0021_auto_20210714_1404"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discoveredfile",
            name="content_hash",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=128,
                validators=[
                    spices.django3.validators.validate_not_blank_string__allow_null
                ],
            ),
        ),
        migrations.AlterField(
            model_name="discoveredfile",
            name="original_download_url",
            field=models.TextField(blank=True),
        ),
    ]
